name: build

on:
  push:
    branches: ["your-branch"]

env:
  REGISTRY_IMAGE: ghcr.io/lurian/sample

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          secrets: |
            "git_auth=${{ secrets.GIT_AUTH_CREDENTIALS }}"
          push: true
          tags: |
            ${{ env.REGISTRY_IMAGE }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY_IMAGE }}:${{ github.sha }}  

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ env.IMAGE_TAG }}
