image:
  repository: edgedb/edgedb
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}
replicas: 1

env:
- name: EDGEDB_SERVER_ADMIN_UI
  value: enabled
storage:
  enabled: true
  className: "local-path"
  storage: "10Gi"

