{{- if .Values.security.tls.enabled }}

{{- if .Values.security.tls.cert }}
{{- if .Values.security.tls.secret }}
{{- fail "You cannot provide both cert and secret" }}
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "gel.fullname" . }}-cert
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  secretName: {{ include "gel.tlsSecretName" . }}
  secretTemplate:
    labels:
      {{- include "gel.labels" . | nindent 6 }}
  {{ toYaml .Values.security.tls.cert | nindent 2 }}
{{- end }}

{{- end }}
