{{- if not .Values.security.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gel.fullname" . }}-server-password
  labels:
    {{- include "gel.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ $password := include "gel.password" . }}{{ $password | b64enc | quote }}
{{- end }}
