apiVersion: v1
kind: Service
metadata:
  name: {{ include "gel.fullname" . }}
  labels:
    {{- include "gel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5656
    protocol: TCP
  selector:
    {{- include "gel.selectorLabels" . | nindent 4 }}
