{{- if not .Values.security.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edgedb.fullname" . }}-server-password
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    {{- include "edgedb.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ $password := include "edgedb.password" . }}{{ $password | b64enc | quote }}
  edgedbBackendDsn: {{ printf "edgedb://edgedb:%s@%s.%s.svc.cluster.local:5656" $password (include "edgedb.fullname" .) .Release.Namespace | b64enc | quote }}
{{- end }}
