{{- if not .Values.security.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edgedb.fullname" . }}-server-password
  labels:
    {{- include "edgedb.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ randAlphaNum 20 | b64enc | quote }}
{{ end }}
