image:
  repository: gel/gel
  pullPolicy: IfNotPresent
  tag:

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}
replicas: 1

security:
  # password: 
  #   secret: ""
  #   key: ""
  tls:
    enabled: false
    # Provide the template for a cert-manager certificate
    # Leave out secretName and secretTemplate if you want the chart to create a certificate
    # with cert-manager
    #
    # cert:
    #   dnsNames:
    #   - "lurian.dev"
    #   issuerRef:
    #     name: selfsigned-issuer
    #     kind: ClusterIssuer
    secret: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}

env: []
volumes: []
volumeMounts: []

envPrefix: "GEL"

service:
  type: ClusterIP
  port: 5656

storage:
  enabled: true
  className: ""
  storage: "10Gi"

postgres:
  enabled: false
  # Can also just be a string postgres://mypostgres:5432/gel
  # dsn:
  #   valueFrom:
  #     secretKeyRef:
  #       name: gel-postgres-app
  #       key: uri
