image:
  repository: gel/gel
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}
replicas: 1

env:
- name: GEL_SERVER_ADMIN_UI
  value: enabled
storage:
  enabled: true
  className: "local-path"
  storage: "10Gi"

